# Generated by Django 5.1.2 on 2024-10-13 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_document_key_concepts'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='key_concept',
            field=models.CharField(default='Unspecified Concept', max_length=255),
            preserve_default=False,
        ),
    ]
