# Generated by Django 5.1.2 on 2024-10-13 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_topic_key_concept'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='key_concept',
            field=models.CharField(default='Unspecified Concept', max_length=255),
        ),
    ]
