# Generated by Django 5.1.2 on 2024-10-13 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_mcq'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MCQ',
        ),
    ]
