# Generated by Django 5.1.2 on 2024-10-13 11:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_delete_mcq'),
    ]

    operations = [
        migrations.CreateModel(
            name='MCQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('correct_answer', models.CharField(max_length=255)),
                ('options', models.JSONField(default=list)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mcqs', to='main_app.topic')),
            ],
        ),
    ]
